version: '3'

services:
  app:
    build: .
    container_name: app
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app
  app_postgres:
    container_name: app_postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
    ports:
      - 5432:5432
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql
